# Generated by Django 4.2.4 on 2023-09-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=250)),
                ('Phone', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=50)),
                ('Message', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
