# Generated by Django 4.2.4 on 2023-09-09 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sms',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='sms',
            old_name='Message',
            new_name='sms',
        ),
        migrations.RenameField(
            model_name='sms',
            old_name='Phone',
            new_name='tel',
        ),
    ]
