# Generated by Django 4.2.4 on 2023-09-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rename_email_sms_email_rename_message_sms_sms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='UserName',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
