# Generated by Django 4.2.4 on 2023-09-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_sms_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='sms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
